"""add house model

Revision ID: ed5135edd85e
Revises: 20240319_initial
Create Date: 2024-03-20 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5135edd85e'
down_revision: Union[str, None] = '20240319_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'houses', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('houses', 'owner_id')
    op.drop_column('houses', 'description')
    # ### end Alembic commands ###