"""make_bim_house_id_nullable

Revision ID: 1b116a96a105
Revises: make_bim_fields_nullable
Create Date: 2025-07-04 21:00:39.162022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b116a96a105'
down_revision: Union[str, None] = 'make_bim_fields_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bim_models', 'software_origin',
               existing_type=postgresql.ENUM('REVIT', 'ARCHICAD', 'SKETCHUP', 'AUTOCAD', 'BLENDER', 'OTHER', name='bimsoftware'),
               nullable=False)
    op.alter_column('bim_models', 'level_of_detail',
               existing_type=postgresql.ENUM('LOD_100', 'LOD_200', 'LOD_300', 'LOD_400', 'LOD_500', name='bimlevelofdetail'),
               nullable=False)
    op.alter_column('bim_models', 'house_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_document_versions_tenant_id'), table_name='document_versions')
    op.drop_column('document_versions', 'tenant_id')
    op.drop_column('document_versions', 'file_url')
    op.drop_column('document_versions', 'change_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('change_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document_versions', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('document_versions', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_document_versions_tenant_id'), 'document_versions', ['tenant_id'], unique=False)
    op.alter_column('bim_models', 'house_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bim_models', 'level_of_detail',
               existing_type=postgresql.ENUM('LOD_100', 'LOD_200', 'LOD_300', 'LOD_400', 'LOD_500', name='bimlevelofdetail'),
               nullable=True)
    op.alter_column('bim_models', 'software_origin',
               existing_type=postgresql.ENUM('REVIT', 'ARCHICAD', 'SKETCHUP', 'AUTOCAD', 'BLENDER', 'OTHER', name='bimsoftware'),
               nullable=True)
    # ### end Alembic commands ###
