"""make_bim_fields_nullable_final

Revision ID: 589a715e2577
Revises: 0dd41f5fdbdf
Create Date: 2025-07-06 11:56:55.752012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '589a715e2577'
down_revision: Union[str, None] = '0dd41f5fdbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bim_models', 'software_origin',
               existing_type=postgresql.ENUM('REVIT', 'ARCHICAD', 'SKETCHUP', 'AUTOCAD', 'BLENDER', 'OTHER', name='bimsoftware'),
               nullable=True)
    op.alter_column('bim_models', 'level_of_detail',
               existing_type=postgresql.ENUM('LOD_100', 'LOD_200', 'LOD_300', 'LOD_400', 'LOD_500', name='bimlevelofdetail'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bim_models', 'level_of_detail',
               existing_type=postgresql.ENUM('LOD_100', 'LOD_200', 'LOD_300', 'LOD_400', 'LOD_500', name='bimlevelofdetail'),
               nullable=False)
    op.alter_column('bim_models', 'software_origin',
               existing_type=postgresql.ENUM('REVIT', 'ARCHICAD', 'SKETCHUP', 'AUTOCAD', 'BLENDER', 'OTHER', name='bimsoftware'),
               nullable=False)
    # ### end Alembic commands ###
