"""add_manual_fields_to_documents

Revision ID: ad7a7daa5866
Revises: 589a715e2577
Create Date: 2025-07-07 14:34:22.814684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision: str = 'ad7a7daa5866'
down_revision: Union[str, None] = '589a715e2577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('device_name', String(), nullable=True))
    op.add_column('documents', sa.Column('brand', String(), nullable=True))
    op.add_column('documents', sa.Column('model', String(), nullable=True))
    op.add_column('documents', sa.Column('external_link', String(), nullable=True))
    op.add_column('documents', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'room_id')
    op.drop_column('documents', 'external_link')
    op.drop_column('documents', 'model')
    op.drop_column('documents', 'brand')
    op.drop_column('documents', 'device_name')
    # ### end Alembic commands ###
